### ISSUE TITLE
[Field name or General]: Update the intl dependency to the latest version

### ISSUE THREAD

**Issue by FearlessHyena** [flutter-form-builder-ecosystem/form_builder_cupertino_fields#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

0.2.1

### What you'd like to happen

```Markdown
I'd like the package to update the `intl` dependency to the latest version which [has been released](https://pub.dev/packages/intl) recently
```

**Comment by FearlessHyena** [comment]
@deandreamatias I submitted a PR for this several months ago. Can you please check and merge it?

**Comment by Cuiboy** [comment]
did this merge never make it in? It's currently breaking my app at the moment

**Comment by deandreamatias** [comment]
I will update the new version to pub.dev today
