### ISSUE TITLE
Add FormBuilderCupertinoDateTimePicker

### ISSUE THREAD

**Issue by gotecq-thudang** [flutter-form-builder-ecosystem/form_builder_cupertino_fields#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

0.2.0

### What you'd like to happen

```Markdown
Can you implement CupertinoDateTimePicker for form builder
```

**Comment by baptistesx** [comment]
That would be very nice yeah :)

Isn't it possible to develop FormBuilderDateTimePicker.adaptative() (and others) as some basic Flutter widgets have ?

**Comment by deandreamatias** [comment]
If someone want to create a PR with adding this widget, I will review and merge

**Comment by deandreamatias** [comment]
Duplicated #3
